{
 "title": "Application Monitoring Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running Application Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"application\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Pod Restarts in Time Range",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  increase(kube_pod_container_status_restarts_total{namespace=\"application\"}[$__range])\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Application Pod Ready Status",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  kube_pod_status_ready{namespace=\"application\", condition=\"true\"}\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{namespace=\"application\"}[5m])\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{namespace=\"application\"}\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}