apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    majorVersion: "3"
    meta.helm.sh/release-name: opensearch
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2026-06-17T03:10:33Z"
  generation: 1
  labels:
    app.kubernetes.io/component: opensearch-cluster-single
    app.kubernetes.io/instance: opensearch
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/version: 3.6.0
    helm.sh/chart: opensearch-3.6.0
  name: opensearch-cluster-single
  namespace: monitoring
  resourceVersion: "1800461"
  uid: 7c7d4236-53b1-4843-8180-2be052e29984
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: opensearch
      app.kubernetes.io/name: opensearch
  serviceName: opensearch-cluster-single-headless
  template:
    metadata:
      annotations:
        configchecksum: 4e6da6f24a79fb172f152ec4e3bb5d9208477caae7a3e89e7f5834a81e8f30e
      labels:
        app.kubernetes.io/component: opensearch-cluster-single
        app.kubernetes.io/instance: opensearch
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: opensearch
        app.kubernetes.io/version: 3.6.0
        helm.sh/chart: opensearch-3.6.0
      name: opensearch-cluster-single
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - opensearch
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - opensearch
              topologyKey: kubernetes.io/hostname
            weight: 1
      automountServiceAccountToken: false
      containers:
      - env:
        - name: node.name
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: opensearch-cluster-master-headless
        - name: cluster.name
          value: opensearch-cluster
        - name: network.host
          value: 0.0.0.0
        - name: OPENSEARCH_JAVA_OPTS
          value: -Xmx512M -Xms512M
        - name: node.roles
          value: master,ingest,data,remote_cluster_client,
        - name: discovery.type
          value: single-node
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: "true"
        - name: DISABLE_SECURITY_PLUGIN
          value: "true"
        image: opensearchproject/opensearch:3.6.0
        imagePullPolicy: IfNotPresent
        name: opensearch
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        - containerPort: 9600
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9200
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9200
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch-cluster-single
        - mountPath: /usr/share/opensearch/config/opensearch.yml
          name: config-emptydir
          subPath: opensearch.yml
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
      - args:
        - chown -R 1000:1000 /usr/share/opensearch/data
        command:
        - sh
        - -c
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: fsgroup-volume
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch-cluster-single
      - command:
        - sh
        - -c
        - |
          #!/usr/bin/env bash
          cp -r /tmp/configfolder/*  /tmp/config/
        image: opensearchproject/opensearch:3.6.0
        imagePullPolicy: IfNotPresent
        name: configfile
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/config/
          name: config-emptydir
        - mountPath: /tmp/configfolder/opensearch.yml
          name: config
          subPath: opensearch.yml
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          defaultMode: 420
          name: opensearch-cluster-single-config
        name: config
      - emptyDir: {}
        name: config-emptydir
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: opensearch-cluster-single
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: opensearch-cluster-single-64468d6c98
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: opensearch-cluster-single-64468d6c98
  updatedReplicas: 1
