grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin123

  service:
    type: ClusterIP

  defaultDashboardsEnabled: true

  deploymentStrategy:
    type: Recreate

  initChownData:
    enabled: false

  persistence:
    enabled: true
    type: pvc
    existingClaim: grafana-storage

  smtp:
    existingSecret: grafana-smtp-credentials
    userKey: user
    passwordKey: password

  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      from_address: thdatwater1911@gmail.com
      from_name: "Thesis Security Monitoring"
      skip_verify: false
      startTLS_policy: MandatoryStartTLS

  sidecar:
    dashboards:
      enabled: true

    datasources:
      enabled: true

prometheus:
  enabled: true

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 7d

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: false

prometheusOperator:
  enabled: true

prometheus-node-exporter:
  enabled: false